# Generated by Django 2.1.4 on 2018-12-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20181225_1256'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='my_books',
            field=models.ManyToManyField(blank=True, related_name='book_got', to='core.Book'),
        ),
    ]
