# Generated by Django 2.1.4 on 2018-12-24 08:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181224_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='book_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
