# Generated by Django 2.1.4 on 2018-12-25 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181225_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='quantity',
            new_name='owners',
        ),
    ]
