# Generated by Django 2.1.4 on 2018-12-25 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20181225_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='owners',
        ),
    ]
