# Generated by Django 2.1.4 on 2018-12-25 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_book_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='quantity',
        ),
    ]
